name: label-maker
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.0
  - rasterio>=1.2.10,=1.2
  - boto3>=1.21.8,=1.21
  - pip:
    - Cerberus~=1.3.4
    - geojson~=2.5.0
    - mapbox-vector-tile~=1.2.1
    - mercantile~=1.2.1
    - numpy~=1.22.2
    - Pillow~=9.0.1
    - rasterio[s3]~=1.2.10
    - requests~=2.27.1
    - Shapely~=1.8.1.post1
    - tilepie~=0.2.1
    - tqdm~=4.62.3
