name: label-maker
channels:
  - conda-forge
dependencies:
  - python=3.9
  - boto3
  - Cerberus
  - geojson
  - mapbox-vector-tile
  - mercantile
  - numpy
  - Pillow
  - rasterio
  - requests
  - Shapely
  - tilepie
  - tqdm
